-- Table quickorder.ASIGNACION_MESERO

CREATE TABLE "quickorder"."ASIGNACION_MESERO"(
 "ASIGNACION_MESERO_ID" Integer NOT NULL,
 "EMPLEADO_ID" Integer NOT NULL,
 "MESA_ID" Character(20) NOT NULL,
 "ACTIVO" Character(1) NOT NULL,
 "FECHA_ASIGNACION" Date NOT NULL,
 "FECHA_REVOCACION" Date
)
TABLESPACE "ts_quickorder"
;

-- Create indexes for table quickorder.ASIGNACION_MESERO

CREATE INDEX "IDX_ASIGNACION_MESERO_EMP" ON "quickorder"."ASIGNACION_MESERO" ("EMPLEADO_ID")
;

CREATE INDEX "IDX_ASIGNACION_MESERO_MESA" ON "quickorder"."ASIGNACION_MESERO" ("MESA_ID")
;

CREATE INDEX "IDX_ASIGNACION_MESERO_ACTIVO" ON "quickorder"."ASIGNACION_MESERO" ()
;

-- Add keys for table quickorder.ASIGNACION_MESERO

ALTER TABLE "quickorder"."ASIGNACION_MESERO" ADD CONSTRAINT "IDXPK_ASIGNACION_MESERO" PRIMARY KEY ("ASIGNACION_MESERO_ID")
;