-- Table quickorder.AUDITA_TABLAS

CREATE TABLE "quickorder"."AUDITA_TABLAS"(
 "AUDIT_ID" Integer NOT NULL,
 "TABLA_ID" Integer NOT NULL,
 "EMPLEADO_ID" Integer NOT NULL,
 "PRIMARY_KEY" Integer NOT NULL,
 "FECHA_ACTUALIZACION" Timestamp NOT NULL
)
TABLESPACE "ts_quickorder"
;

-- Create indexes for table quickorder.AUDITA_TABLAS

CREATE INDEX "IDX_MODIFICACION_EMPLEADO" ON "quickorder"."AUDITA_TABLAS" ("EMPLEADO_ID")
;

CREATE INDEX "IDX_MODIFICACION_TABLAS" ON "quickorder"."AUDITA_TABLAS" ("TABLA_ID")
;

-- Add keys for table quickorder.AUDITA_TABLAS

ALTER TABLE "quickorder"."AUDITA_TABLAS" ADD CONSTRAINT "IDXPK_VERSION_ACTUALIZACION" PRIMARY KEY ("AUDIT_ID")
;