-- Table quickorder.PRODUCTO_EN_ORDEN

CREATE TABLE "quickorder"."PRODUCTO_EN_ORDEN"(
 "PRODUCTO_EN_ORDEN_ID" Integer NOT NULL,
 "PRODUCTO_ID" Integer NOT NULL,
 "ORDEN_ID" Integer NOT NULL,
 "ESTATUS_ID" Integer NOT NULL
)
TABLESPACE "ts_quickorder"
;

-- Create indexes for table quickorder.PRODUCTO_EN_ORDEN

CREATE INDEX "IDX_ORDEN_PRODUCTO_ESTATUS" ON "quickorder"."PRODUCTO_EN_ORDEN" ("ESTATUS_ID")
;

CREATE INDEX "IDX_PRODUCTO_ORDEN" ON "quickorder"."PRODUCTO_EN_ORDEN" ("PRODUCTO_ID")
;

CREATE INDEX "IDX_ORDEN_PRODUCTO" ON "quickorder"."PRODUCTO_EN_ORDEN" ("ORDEN_ID")
;

-- Add keys for table quickorder.PRODUCTO_EN_ORDEN

ALTER TABLE "quickorder"."PRODUCTO_EN_ORDEN" ADD CONSTRAINT "IDXPK_ORDEN_PRODUCTO" PRIMARY KEY ("PRODUCTO_EN_ORDEN_ID")
;